# Server Properties =================================
server:
  port: 8080

spring:
  profiles:
    include: public
    group:
      "dev": "dev-setting,common-public"
      "production": "production-setting,common-public"

---
# Spring Properties =================================
spring:
  config:
    activate:
      on-profile: "dev-setting"
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:taskscheduler;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


# Custom Properties =================================
edmstoken:
  admin:
    id: admin
    password: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1


---

# Spring Properties =================================
spring:
  config:
    activate:
      on-profile: "production-setting"
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: auto
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


# Custom Properties =================================
edmstoken:
  admin:
    id: admin
    password: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1

